### ISSUE TITLE
Capistrano v3 support

### ISSUE THREAD

**Issue by seejohnrun** [xijo/capistrano-puma#1]
would be awesome!

**Comment by kyledecot** [comment]
+1 I would really love this!

**Comment by xijo** [comment]
I'll look into capistrano 3 whenever I can find the time to do so and keep you up to date.

**Comment by rubytastic** [comment]
+1 awesome work already done so far, thank you!

**Comment by seejohnrun** [comment]
Woo @johnbellone - thanks!

**Comment by johnbellone** [comment]
@seejohnrun Where you been at you bum? D.C. is missing you!

**Comment by seejohnrun** [comment]
@johnbellone HAPPY BIRTHDAY.  Also, DC is farrrrrr - but I'll be there soonish, and miss ya
